### PR TITLE
fix: correct invalid react version constraint

### PR DESCRIPTION
**Pull request by dsherret**
The version constraint was invalid and accepted any react version `>=16.8.0`.

```
> import semver from "npm:semver"
> semver.satisfies("21.0.1", ">=16.8.0 && <=^19.0.0", { loose: true })
true
```

### CODE REVIEW

**Review by dodgez-stripe — APPROVED** [review]
Good catch, thanks!

**Comment by dodgez-stripe** [comment]
Package version 3.1.1 contains this fix: https://www.npmjs.com/package/@stripe/react-stripe-js/v/3.1.1

**Comment by dsherret** [comment]
Great, thanks!

**Comment by rado-stripe** [comment]
:wave: Hi David, thanks for the bug report!

**Pull request merged**
